all:
	mkdir ./content
	mkdir ./content/models/
	mkdir ./content/results/

fclean:
	rm -rf ./content/models/*
	rm -rf ./content/tf-levenberg-marquadt

clean:
	rm -rf ./content/models/*
	rm -rf ./content/results/*